---
title: "Week9"
author: "Jannelle Legg"
date: "October 21, 2014"
output: html_document
---

Working through Jockers


```{r}
voltadata <- scan("~/Clio3/week9/The_Volta_Review.txt", what="character", sep="\n")

Hmm.. need to find a .txt example online. GOT ONE!
DMJ1872_11_14 <- scan("http://archive.org/stream/GuDeafmutesjo18721114_201311/gu_deafmutesjo18721114_djvu.txt", what="character", sep="\n")

voltadata
voltadata[1]

#lets look for the beginning of the text: oh, this one is huge. let's work with DMJ
# soo many errors..

buffAndBlue <- scan("http://archive.org/stream/gu_buffandblue19411017/gu_buffandblue19411017_djvu.txt", what="character", sep="\n")

buffAndBlue

#okay, first line of the paper should be "Welcome Students", the last is "SPORTSWEAR, THIRD FLOOR"

buffAndBlue[9]

start <- which(buffAndBlue == "WELCOME STUDENTS")
end <- which(buffAndBlue == "SPORTSWEAR, THIRD FLOOR")

# failure - lets try this with something easier.

text.v <- scan("http://www.gutenberg.org/cache/epub/2701/pg2701.txt", what="character", sep="\n")

text.v
text.v[1]

# figure out which lines = beginning/end
start.v <- which(text.v == "CHAPTER 1. Loomings.")
end.v <- which(text.v == "orphan.")

start.v
end.v

# figure out the length (how many newlines in the text)

length(text.v)

# strip out metadata from the book 

start.metadata.v <- text.v [1:start.v -1]
end.metadata.v <- text.v[ (end.v+1) :length(text.v)]
metadata.v <- c(start.metadata.v, end.metadata.v)
novel.lines.v <- text.v[start.v:end.v]

#looking at what we've got:
text.v[start.v]
text.v[start.v-1]
text.v[end.v]
text.v[end.v+1]

length(text.v)
length(novel.lines.v)
length(text.v) - length(novel.lines.v)


# joining each line into ONE comprehensive variable

novel.v <- paste(novel.lines.v, collapse= " ")
length(novel.v)
novel.v[1]

#make it all lowercase:

novel.lower.v <- tolower(novel.v)

# split text strings - identify word boundaries with strsplit to make a LIST of words
moby.words.1 <- strsplit(novel.lower.v, "\\W")

# keeping track of type of object:
class(novel.lower.v)
class(moby.words.1)

str(moby.words.1)

# making it not a list anymore:
moby.word.v <- unlist(moby.words.1)

# identifying blanks (former punctuation)
not.blanks.v <- which(moby.word.v!="")
not.blanks.v

# now that non-blanks are identified, overwrite moby to contain  words

moby.word.v <- moby.word.v[not.blanks.v]
moby.word.v

# identifying word positions:

moby.word.v[2014]
moby.word.v[2345:2355]


mypositions.v <- c(4,5,6)
moby.word.v[mypositions.v]
# same thing as:
moby.word.v[c(4,5,6)]

# finding position for a specific word:
which(moby.word.v=="whale")

moby.word.v[which(moby.word.v=="whale")]

```


```{r}
#beginning analysis

length(moby.word.v[which(moby.word.v=="whale")])
length(moby.word.v)

#percentage of whale occurences

whale.hits.v <- length(moby.word.v[which(moby.word.v=="whale")])
total.words.v <- length(moby.word.v)
whale.hits.v/total.words.v

#how many words he uses:
length(unique(moby.word.v))

# how often he uses words, which words are faves
moby.freqs.t <- table(moby.word.v)
sorted.moby.freqs.t <- sort(moby.freqs.t , decreasing=TRUE)

sorted.moby.freqs.t[1:10]
plot(sorted.moby.freqs.t[1:10])
#fancy plot:
plot(sorted.moby.freqs.t[1:10], type="b",
     xlab="Top Ten Words", ylab="Word Count", xaxt ="n")
axis(1,1:10, labels=names (sorted.moby.freqs.t[1:10]))
```

```{r}
#chapter 3

sorted.moby.freqs.t["he"]
sorted.moby.freqs.t["she"]
sorted.moby.freqs.t["him"]
sorted.moby.freqs.t["her"]


# how much more often "him" than "her"

sorted.moby.freqs.t["him"]/sorted.moby.freqs.t["her"]
sorted.moby.freqs.t["he"]/sorted.moby.freqs.t["she"]

# looking at percentages = more useful

sorted.moby.rel.freqs.t <- 100*(sorted.moby.freqs.t/sum(sorted.moby.freqs.t))

sorted.moby.rel.freqs.t["the"]

# plot by percentage

plot(sorted.moby.rel.freqs.t[1:10], type="b",
     xlab="Top Ten Words", ylab="Percentage of Full Text", xaxt ="n")
axis(1,1:10, labels=names(sorted.moby.rel.freqs.t [1:10]))


```

```{r}
# Chapter 4

# dispersion plots look at order of words as "time"
# first have to create a sequence - from first word to last word.

n.time.v <- seq(1:length(moby.word.v))

# now n.time.v = all the positions of every word in the book

whales.v <- which(moby.word.v == "whale")
whales.v

w.count.v <- rep(NA, length(n.time.v))
w.count.v[whales.v] <- 1

plot(w.count.v, main="Dispersion Plot of 'whale' in Moby Dick",
     xlab="Novel Time", ylab="whale", type="h", ylim=c(0,1), yaxt='n')

# same for ahab
ahabs.v <- which(moby.word.v == "ahab") #find 'ahab'
a.count.v <- rep(NA, length(n.time.v))
#change 'w' to 'a' to keep whales in separate variables
a.count.v[ahabs.v] <- 1 #mark the occurances with a 1
plot(a.count.v, main="Dispersion Plot of 'ahab' in Moby Dick",
     xlab="Novel Time", ylab="ahab", type="h", ylim=c(0,1), yaxt='n')

#same for ship  - this is me and it worked!

ships.v <- which(moby.word.v == "ship") #find 'ship'
s.count.v <- rep(NA, length(n.time.v))
#change 'a' to 's' to keep ships in separate variables
s.count.v[ships.v] <- 1 #mark the occurances with a 1
plot(s.count.v, main="Dispersion Plot of 'ship' in Moby Dick",
     xlab="Novel Time", ylab="ship", type="h", ylim=c(0,1), yaxt='n')

```

```{r}
# now grep stuff.. not clearing the workspace.

rm(list = ls())
ls()

text.v <- scan("http://www.gutenberg.org/cache/epub/2701/pg2701.txt", what="character", sep="\n")
start.v <- which(text.v == "CHAPTER 1. Loomings.")
end.v <- which(text.v == "orphan.")
novel.lines.v <- text.v[start.v:end.v]

novel.lines.v

#grabbing the chapter breaks by looking at how the txt file is structured

chap.positions.v <- grep("^CHAPTER \\d", novel.lines.v)
novel.lines.v[chap.positions.v]

chap.positions.v

# this marks all the beginnings of chapters - need to mark ends too

novel.lines.v <- c(novel.lines.v, "END")
last.position.v <- length(novel.lines.v)
chap.positions.v <- c(chap.positions.v , last.position.v)

chap.positions.v

chap.positions.v[2]

for(i in 1:length(chap.positions.v)) {
  print(chap.positions.v[i])
}

# makes it easier to see which chapter is where:

for(i in 1:length(chap.positions.v)) { 
  print(paste("Chapter ",i, " begins at position ",
              chap.positions.v[i]), sep="")
  }


# creating empty list objects to store data

chapter.raws.1 <- list()
chapter.freqs.1 <- list()



```

